### ISSUE TITLE
Cannot save or custom save when add big local image

### ISSUE THREAD

**Issue by nobutsta** [jimdoescode/jqScribble#12]
Hello,
I can't export (or save) the drawing when I add big (1200x800) image to the canvas. It says 

SecurityError: The operation is insecure.
if(!this.blank)saveFunction(this.canvas.toDataURL(settings.saveMimeType));

And it's not work when add local image with the same size too!
Image URL : http://www.ifreewallpaper.com/wallpapers_download/mobile/1200_800_wallpapers/20110904/B/B_orangeflow_8ylkuhrb.jpg

Please suggest.

**Comment by jimdoescode** [comment]
It seems this is a CORS issue. http://stackoverflow.com/questions/25753754/canvas-todataurl-security-error-the-operation-is-insecure
