### ISSUE TITLE
Multiple jqScribble doesn't work properly in the same page.

### ISSUE THREAD

**Issue by herakles86** [jimdoescode/jqScribble#14]
I put two jaScribble in the same html page.

```html
<body>
    <div id="emp_sig" style="border:1px solid red; width:80px; height:20px"></div>
    <div id="cust_sig" style="border:1px solid red; width:80px; height:20px"></div>
</body>
```
```javascript
$("#emp_sig").jqScribble();
$("#cust_sig").jqScribble();
```
when I drawn in the first canvas, the image appeared in the second one.

**Comment by jimdoescode** [comment]
The way to have multiple instances is to use [multiple selectors](https://api.jquery.com/multiple-selector/)
```javascript
$("#emp_sig, #cust_sig").jqScribble();
```

**Comment by herakles86** [comment]
I find that I am using the old version which I got from jquery website.

now i download the latest version, it works.

Thank you.
