### ISSUE TITLE
.save() function should return a success or error callback if canvas is not drawn or create an isBlank function

### ISSUE THREAD

**Issue by danicomas** [jimdoescode/jqScribble#17]
```
Current behavior
.save() function is only fired if canvas was drawn

Expected behavior
.save() function should return a success or error callback if canvas is not drawn
```

**Comment by jimdoescode** [comment]
That's an interesting idea but `.save()` can't return a success or error callback because then it would not be chainable with other jqScribble methods.

Let's continue the discussion but I'm going to close this since it's more a feature request than an issue.

**Comment by danicomas** [comment]
I have created an isBlank function I hope it is well for you @jimdoescode
