### ISSUE TITLE
How to put a dot after clicking on the plugin area

### ISSUE THREAD

**Issue by AliTajari** [jimdoescode/jqScribble#22]
Hi. Sorry, I can't speak English very well.
I need to put a point after click on the plugin area. I want to use this plugin for a light pen device.
please help me.

**Comment by jimdoescode** [comment]
If you need to make a point after a click you should make a [custom brush](https://github.com/jimdoescode/jqScribble#creating-new-brushes) and use the `strokeEnd` method.

I'm closing this issue as it's not really a bug or feature request.
